### ISSUE TITLE
Problems executing the Code Base

### ISSUE THREAD

**Issue by sidney1505** [lmb-freiburg/ldce#1]
Hi,

thank you for your nice work! I tried executing it, but I got a bit confused about your https://github.com/lmb-freiburg/ldce/blob/9df1389f4540e7ac12df9fb8445b2ae7b805d747/scripts/ldce.py#L28 - where does the referred "src" package come from? It is neither mentioned in the environment.yaml, nor it is present in the code base.

Best,
Sidney

**Comment by SimonSchrodi** [comment]
Hi Sidney,

thanks for pointing this out! Actually, LDCE does not use spatial priors neither from [CLIPSeg](https://arxiv.org/abs/2112.10003) nor [SAM](https://arxiv.org/abs/2304.02643) and, thus, you don't need it to run LDCE. I've moved this into a try-except statement (https://github.com/lmb-freiburg/ldce/commit/361b38ec0212d164813adb6919e6c40c42b0cde2) s.t. the code does not error because of it.

If you would like to run with spatial prior, you would need to create the folder `src` and clone the respective repository there. Note that we haven't tested the spatial prior implementation, so there may be unforeseen errors. 

Best,
Simon
